### ISSUE TITLE
Page Broken - Cannot read property "name" of undefined

### ISSUE THREAD

**Issue by lorissa-b** [EmmaRamirez/nuzlocke-generator#251] opened 2020-05-31 23:34 UTC
**Steps to Reproduce**

- Get a fresh instance of the generator (this doesn't work if you've successfully changed the team background)
- Have the "Team" box set to the Route 1 background
- Go to change the wallpaper
- Change it to the Route 1 background
- Page should go blank

**Expected Result**
Team box background should stay the same

**Console Error**
`TypeError: Cannot read property 'name' of undefined
    at ResultBase.renderContainer (VM20970 Result.tsx:101)
    at ResultBase.render (VM20970 Result.tsx:277)
    at gi (VM19766 react-dom.production.min.js:182)
    at fi (VM19766 react-dom.production.min.js:181)
    at Rj (VM19766 react-dom.production.min.js:263)
    at Qj (VM19766 react-dom.production.min.js:246)
    at Kj (VM19766 react-dom.production.min.js:246)
    at yj (VM19766 react-dom.production.min.js:239)
    at eval (VM19766 react-dom.production.min.js:123)
    at exports.unstable_runWithPriority (VM19768 scheduler.production.min.js:19)`
from `VM19822 rollbar.umd.min.js:2`

**Comment by EmmaRamirez** [comment] 2020-06-02 04:19
I wonder if some of the other changes I made to boxes have unintentionally fixed this, as I can't seem to reproduce it (using a fresh instances)

**Comment by EmmaRamirez** [comment] 2020-10-11 03:39
Closing for now as I can't reproduce.

**Closed by EmmaRamirez** 2020-10-11 03:39 UTC
